apiVersion: apps/v1
kind: Deployment
metadata:
  name: hivebox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hivebox
  template:
    metadata:
      labels:
        app: hivebox
    spec:
      containers:
      - name: hivebox-container
        image: hivebox:test-1
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: hivebox-config
